## Week 5 Assignment

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import random
from random import randrange
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.utils import shuffle
from sklearn.datasets import load_breast_cancer

## Load the data frame and shuffle the rows so that we don't have bias in k fold method.

In [146]:
# os.getcwd()
dataset = pd.read_csv('iris.csv')
dataset = shuffle(dataset)
dataset.describe()
X = dataset[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].values 
Y = dataset[['species']].values

In [17]:
classifier1 = LogisticRegression()
classifier1.fit(X,Y)
print(classifier1.intercept_)
print(classifier1.coef_)

[ 0.26560617  1.08542374 -1.21471458]
[[ 0.41498833  1.46129739 -2.26214118 -1.0290951 ]
 [ 0.41663969 -1.60083319  0.57765763 -1.38553843]
 [-1.70752515 -1.53426834  2.47097168  2.55538211]]


/home/uozdemir/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/uozdemir/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/uozdemir/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


# Split the dataframe into two subsets

In [147]:
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.5)

In [148]:
sc_X=StandardScaler()
x_train=sc_X.fit_transform(x_train)
x_test=sc_X.transform(x_test)

In [149]:
classifier = LogisticRegression()
classifier.fit(x_train, y_train)

/home/uozdemir/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/uozdemir/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/uozdemir/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [150]:
print('intercept:', classifier.intercept_)
print('coefficient:', classifier.coef_)

intercept: [-0.70714138 -0.87232422 -2.3874576 ]
coefficient: [[-0.97866325  1.05462493 -1.48821863 -1.30950581]
 [ 0.24149292 -0.92704169  0.84918041 -0.61851648]
 [ 0.06747457  0.02217927  1.0218412   1.75392299]]


In [151]:
#Predicting the Test Set Result
y_pred = classifier.predict(x_test)

In [152]:
#Create Confusion Matrix for Evaluation
cm = confusion_matrix(y_test, y_pred)

In [153]:
print(y_pred)

['virginica' 'virginica' 'versicolor' 'setosa' 'versicolor' 'versicolor'
 'versicolor' 'virginica' 'virginica' 'setosa' 'virginica' 'virginica'
 'setosa' 'setosa' 'virginica' 'virginica' 'setosa' 'virginica'
 'virginica' 'versicolor' 'setosa' 'setosa' 'virginica' 'setosa'
 'virginica' 'virginica' 'setosa' 'virginica' 'virginica' 'virginica'
 'virginica' 'virginica' 'virginica' 'setosa' 'virginica' 'virginica'
 'virginica' 'versicolor' 'virginica' 'versicolor' 'setosa' 'setosa'
 'versicolor' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'virginica' 'virginica' 'versicolor' 'versicolor'
 'virginica' 'versicolor' 'setosa' 'virginica' 'versicolor' 'virginica'
 'setosa' 'setosa' 'versicolor' 'virginica' 'virginica' 'versicolor'
 'versicolor' 'virginica' 'versicolor' 'virginica' 'virginica'
 'versicolor' 'virginica' 'setosa' 'virginica' 'setosa']


In [154]:
count = 0
index = 0
for pred in y_pred:
    if pred == y_test[index]:
        count = count + 1
    else:
        pass
    index = index + 1
count/len(y_train)

0.9066666666666666

The model predicts the outcome with 91% accuracy.

## LOOCV

In [173]:
sc_X = StandardScaler()
X = sc_X.fit_transform(X)
accuracy = 0.0
for i in range(X.shape[0]):
    x_train = np.delete(X, i, axis = 0)
    y_train = np.delete(Y, i)
    
    x_test = X[i,:]
    y_test = Y[i]
    
    classifier = LogisticRegression()
    classifier.fit(x_train, y_train)
    
    y_pred = classifier.predict(x_test.reshape(1, -1))
    cm = confusion_matrix(y_test, y_pred)

    count = 0
    index = 0
    for pred in y_pred:
        if pred == y_test[index]:
            count = count + 1
        else:
            pass
        index = index + 1
    accuracy = accuracy + count/len(y_pred)

totalAccuracy = accuracy/X.shape[0]


/home/uozdemir/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/uozdemir/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/uozdemir/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/uozdemir/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/uozdemir/anaconda3/lib/python3.7/site-packages/sklearn/linea

In [138]:
totalAccuracy

0.8933333333333334

## K-Fold

In [213]:
def kFoldMethod(X, Y, kFold):
    foldTimes = len(X)/kFold
    accuracy = 0.0
    for n in (np.arange(foldTimes)):
        rowIndicesToRemove = np.arange(n*kFold,(n+1)*kFold)
        rowIndicesToRemove = [ int(x) for x in rowIndicesToRemove ]

        x_train = np.delete(X,rowIndicesToRemove,axis = 0)
        y_train = np.delete(Y,rowIndicesToRemove,axis = 0)
        
        x_test = X[rowIndicesToRemove[0]:rowIndicesToRemove[kFold-1]+ 1,:]
        y_test = Y[rowIndicesToRemove[0]:rowIndicesToRemove[kFold-1]+ 1]
    
        classifier = LogisticRegression(solver = 'lbfgs', multi_class = 'auto')
        classifier.fit(x_train, y_train)
    
        y_pred = classifier.predict(x_test)
        numberOfTrues = 0
        for index, pred in enumerate(y_pred):
            if pred == y_test[index]:
                numberOfTrues = numberOfTrues + 1
            else:
                pass
        accuracy = accuracy + numberOfTrues/len(y_pred) # Divide number of trues to number of elements in y_pred to get accuracy for each prediction
    totalAccuracy = accuracy/foldTimes
    return totalAccuracy

In [218]:
kFoldMethod(X,Y,1)

/home/uozdemir/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/uozdemir/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/uozdemir/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/uozdemir/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please 

0.9533333333333334